fix users password stored without being hash. Readme Updated
rootstrap/node-ts-api-base-jn pull request #6
Opened 2021-06-24 20:18 UTC by nelegatti

## Pull request type

- [ X ] Bugfix
- [ X ] Documentation content changes

## What is the current behavior?

When executing the Seed command (like yarn db:setup) to insert fake data, the password is stored as plane text, generating issues if we try a login with those fake users

Issue Link: N/A

## What is the new behavior?

- When we run the Seed command, the password hash is generated and stored in the db. Leave the plain value of the password in the console, so developers are able to generate tokens.
- Readme updated.

## Other information
I'm updating this code because I think it may be helpful for others developers who are going to use the node-ts-api-base Project.

2021-06-25 15:44 UTC, EMazzaglia requested changes
As we discussed before, We should remove the console log and hardcode the password for now. 

Thanks :)

2021-06-25 15:44 UTC, EMazzaglia commented on src/database/factories/user.factory.ts
> +  console.log(`UserEmail: ${email} - Password: ${password}`);
Hi Jesus, As we speak recently, I think that we could remove this line and simply hardcode the password for the user. 
Its a good point to discuss with the rest of the team BTW.

2021-06-25 15:44 UTC, EMazzaglia commented on README.md
> +7. Run `ENV=[dev, test, prod] yarn db:setup`.
This is ok, I would create a new script on the package.json such as: 
"dev:db" that runs: "ENV=dev yarn db:setup"
so we can simplify the script execution

2021-06-25 16:10 UTC, nelegatti commented on src/database/factories/user.factory.ts
> +  console.log(`UserEmail: ${email} - Password: ${password}`);
Hey Emiliano, thanks for your comment, it's done. Let's check what the rest of the team think about it

2021-06-25 16:16 UTC, nelegatti commented on README.md
> +7. Run `ENV=[dev, test, prod] yarn db:setup`.
It's a good idea, but I find it cleaner to have a single script in Package.json and define the EnvVariable to use it, rather than having a script in the package.json for each environment (dev:db, test:db, prod:db). What do you think?

2021-06-29 20:41 UTC, nelegatti commented
I'll merge this pull request just for continue moving forward with new code. If someone of you have comments about this PR just let me know and I can make the changes that you consider. Thanks

2021-06-29 20:41 UTC, merged